Updated stemkit-cpp installation script for Windows.
git-svn-id: https://svn.code.sf.net/p/stemkit/code@2225 faf13d3b-af0d-0410-97ba-fcc57a00092e

diff --git a/scripts/install-stemkit-cpp b/scripts/install-stemkit-cpp
--- a/scripts/install-stemkit-cpp
+++ b/scripts/install-stemkit-cpp
@@ -1,34 +1,73 @@
 #!/bin/sh
 
-[ "${#}" != 2 -a "${#}" != 3 ] && {
-  echo "USAGE: ${0} <source-path> <target-path> [<abi>]"
-  exit 2
-}
-
-include_source="${1}/src/include"
-library_source="${1}/bin/lib"
-
-include_target="${2}/include"
-library_target="${2}/lib${3:+-${3}}"
-
-rm -rf "${include_target}"
-mkdir -p "${include_target}"
-include_target=`cd "${include_target}" >/dev/null 2>&1 && pwd`
-
-[ "${include_target:+set}" != set ] && {
-    echo "Cannot figure target folder for header files"
-    exit 3
-}
-
-(
-    cd "${include_source}" && {
-        find . -name .svn -prune -o -type f -print | cpio -vdump "${include_target}"
+main()
+{
+    [ "${#}" -lt 2 ] && {
+      echo "USAGE: ${0} <source-path> <target-path> [<abi> ...]"
+      exit 2
     }
-)
+    source="${1}"
+    target="${2}"
 
-rm -rf "${library_target}"
-mkdir -p "${library_target}"
+    shift
+    shift
 
-find "${library_source}" \( -name "*.lib" -o -name "*.dll" -o -name "*.jar" -o -name "*.s[ol].*" \) -print | {
-    xargs -t -i cp {} "${library_target}"
+    install_includes "${source}" "${target}"
+
+    if [ "${#}" -eq 0 ]; then
+        install_libs "${source}" "${target}"
+    else
+        for abi in "${@}"; do 
+            install_libs "${source}" "${target}" "${abi}"
+        done
+    fi
 }
+
+install_includes()
+{
+    include_source="${1}/src/include"
+    include_target="${2}/include"
+
+    mkdir -p "${include_target}"
+    include_target=`cd "${include_target}" >/dev/null 2>&1 && pwd`
+
+    [ "${include_target:+set}" != set ] && {
+        echo "Cannot figure target folder for header files"
+        exit 3
+    }
+
+    rm -rf "${include_target}"
+    mkdir -p "${include_target}"
+
+    (
+        cd "${include_source}" && {
+            find . -name .svn -prune -o -type f -print | cpio -vdump "${include_target}"
+        }
+    )
+}
+
+install_libs()
+{
+    if [ "${3:+set}" != "set" ]; then
+        library_source="${1}/bin/lib"
+        library_target="${2}/lib"
+    else
+        library_source="${1}/bin/${3}/lib"
+
+        if [ -d "${library_source}" ]; then
+            library_target="${2}/lib${3}"
+        else
+            library_source="${1}/bin/lib"
+            library_target="${2}/lib-${3}"
+        fi
+    fi
+
+    rm -rf "${library_target}"
+    mkdir -p "${library_target}"
+
+    find "${library_source}" \( -name "*.lib" -o -name "*.dll" -o -name "*.jar" -o -name "*.s[ol].*" \) -print | {
+        xargs -t -i cp {} "${library_target}"
+    }
+}
+
+main "${@}"
